sudo: required
dist: trusty
os: linux
language: minimal
env:
  global:
  - PACK=apr
install:
- sudo apt update
- sudo apt install dchroot debootstrap
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/delete
- tar -xf chroot.tar.gz
- ls
- chmod +x -R ./build-scripts/
- cp -r ./build-scripts/ ./chroot
- sudo mount --bind /dev ./chroot/dev/
- sudo chroot ./chroot build-scripts/$PACK.sh
- ls
- build-scripts/empty.sh
- sudo xargs rm -r -f <delete
- find ./chroot/
- tar -zcvf $PACK ./chroot/
deploy:
  provider: bintray
  file: build.json
  user: radimkohout
  key:
    secure: Cgq2Yd9tpy92xNFf73hthdaT/9jddg6S/g3kwRPTtpi10vfvRnPrV98LCvLP5e5tT1QLPUFnJEvpCScJFfje2ADF9fYJSYyayWFIJ4wYEKC7FbPY79pQ00dW1DQB4RCOmRPz60JYKXTSHulhMbdycOLNb4RJVLzt+eeY84o+P55qdri7ClCYZQ78TZw8XZLbVJkhQBCm/argbl/ngq6snwH4aIt14rCrxPQXbMMd51KQt9PVHAUsZkB6UktZAW2G4clKsAjMmK1woZ5GgKTyTZgoNrHBACschMwFcrFdWPiUsvCVj5qNPVKtk6Q2u1ZuAtOgMD9eafEmOqls0140rW65uTvBBRvAb5PqisUGQmV2Gi0qfsNqibnAEUPOQwsrlVLdUrmiqqZdjHihhsdneonPVEyAwxojZuY+vZ3d2Ex2ICugXD0Q10dxdSGm36WlW6+iPJv7jt6J6wnGj+wtouM4EB/fq6ST+Dny5ZnpaQ910wq9sbq+OnrMgKzg33rqGE7xhsnA+DmHW/fVGDpd4nt2Cp4zLQLrJkZrqkJXLir1E+Usvop4Z9nCJLAREF9jUEnohguBM8x3weq1HHPg6rT+/k51ytKhofC//kyN/mIVkNBtzQny6OmWrQLK6UqQWAQP5C5FlbGzwXxm/B/JypJc/1P/Ev82eidTvCGsIrU=
  skip_cleanup: true
after_deploy:
- sudo rm -r ./chroot
