sudo: required
dist: trusty
os: linux
language: minimal
install:
- sudo apt update
- sudo apt install dchroot debootstrap
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.0/chroot.tar.gz
- tar -xf chroot.tar.gz
- sudo chroot ./chroot apr.sh
- ls ./chroot/
