dist: focal
os: linux
language: minimal
env:
  matrix:
  - PACK=unzip
install:
- sudo apt update
- sudo apt install schroot debootstrap git
- wget https://github.com/cli/cli/releases/download/v1.2.0/gh_1.2.0_linux_amd64.deb
- sudo dpkg -i gh_1.2.0_linux_amd64.deb
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/delete
- tar -xf chroot.tar.gz
- ls
- chmod +x -R ./build-scripts/
- cp -r ./build-scripts/ ./chroot
- sudo mount --bind /dev ./chroot/dev/
- travis_wait 150 sudo chroot ./chroot build-scripts/$PACK.sh
- ls
- build-scripts/empty.sh
- sudo xargs rm -r -f <delete
- rm -r ./chroot/build-scripts
#- find ./chroot/
- tar -zcf $PACK -C chroot .
- mkdir out
- cp $PACK ./out/
after_script:
- bash upload.sh
- sudo rm -r ./chroot
