sudo: required
dist: trusty
os: linux
language: minimal
install:
- sudo apt update
- sudo apt install dchroot debootstrap
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
- tar -xf chroot.tar.gz
- ls
- chmod +x -R ./build-scripts/
- cp -r ./build-scripts/ ./chroot
- sudo /etc/init.d/dns-clean restart
- sudo cat /etc/resolv.conf
- sudo chroot ./chroot build-scripts/apr.sh
- ls ./chroot/
