dist: trusty
os: linux
language: minimal
env:
  matrix:
  - PACK=which
  - PACK=zip
  - PACK=apr
install:
- sudo apt update
- sudo apt install dchroot debootstrap git
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/delete
- tar -xf chroot.tar.gz
- ls
- chmod +x -R ./build-scripts/
- cp -r ./build-scripts/ ./chroot
- sudo mount --bind /dev ./chroot/dev/
- sudo chroot ./chroot build-scripts/$PACK.sh
- ls
- build-scripts/empty.sh
- sudo xargs rm -r -f <delete
- rm -r ./chroot/build-scripts
- find ./chroot/
- tar -zcvf $PACK -C chroot .
- mkdir out
- cp $PACK ./out/
#deploy:
#  provider: bintray
#  file: build-scripts/$PACK.json
#  user: radimkohout
#  key:
#    secure: MEXdhdEbG3SiKAuTA/1kPLrSdHFRllLsORGA7t6wXUWhCQ/hvOn0FXG2TnvSLljGGM8qzeUMS71xqrizP9bBjStKdK1GO9UZM3P7bo8Vzq9aFaxlm+66hPOKqUcU+wv/1/dtmta1Mrz7M/vUP8ZH0RXp3AAzbUGlyYP0PAUUS/0qBS8lTNVPpPQVks/T0mYaj9k6QybL/Dn1TV7iYymJoaejH5t+AP5r5dGR7ipovg7efPrvM3PBOgzH2KH6Z1XktfRRwDudbGPhG5VeIH4bmQUP2vUReNUvrGr8+DzWKEv+w/lq/s8ETQGizW3kJqcSWKqGilvchwCke7VQVtGPYVTQlp3Z8MXo1mVgHpZYBx+eiYWsvhaMAmuoEAIpi0krphUPVF+KxL5L5OAeRZgl5h28KdEvStGXNluks0dhTfYFBWMy7woUWw4SE9GyLhtZDv05bQaB3tygTvG26czMH5cOg68EgXbylEuILpcPWMWhSAElvQhX9VlIjwVjwya567ojBskKsF1TafLMhQtX+B3tFDEg72EJ6BGvq4X7iL/chLmiahn/FBKkgj/VdR/iSP5JkXC5o7iMGC/Hvdr76w4l84vHLeYV3aox/n30zvoOJPX8/SSYSWuVL4nNUkJYngbde0N1QP963w7fosHKptM9MwgWu+AxUJQfnIBj9+s=
#  skip_cleanup: true
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN 
#  file: $PACK
#  repo: GarnetOS/packages
#  keep_history: true
#  target_branch: master
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: $PACK
#  skip_cleanup: true
after_script:
- bash upload.sh
- sudo rm -r ./chroot
