dist: focal
os: linux
language: minimal
env:
  matrix:
  - PACK=acpid
  - PACK=apr
  - PACK=autoconf
  - PACK=bubblewrap
  - PACK=cdparanoia
  - PACK=compface
  - PACK=dosfstools
  - PACK=faac
  - PACK=faad2
  - PACK=fdk-aac
  - PACK=fftw
  - PACK=gccgo
  - PACK=gdc
  - PACK=gfortran
  - PACK=glm
  - PACK=gnome-backgrounds
  - PACK=gnome-video-effects
  - PACK=gobjc++
  - PACK=gobjc
  - PACK=haveged
  - PACK=hdparm
  - PACK=hicolor-icon-theme
  - PACK=iso-codes
  - PACK=jansson
  - PACK=jfsutils
  - PACK=joe
  - PACK=libaio
  - PACK=libatasmart
  - PACK=libatomic_ops
  - PACK=libburn
  - PACK=libcddb
  - PACK=libdvdread
  - PACK=libgpg-error
  - PACK=libisofs
  - PACK=liblinear
  - PACK=libmad
  - PACK=libmnl
  - PACK=libndb
  - PACK=libnl
  - PACK=libogg
  - PACK=libpaper
  - PACK=librep
  - PACK=libsigsegv
  - PACK=libspiro
  - PACK=libstatgrab
  - PACK=libuv
  - PACK=lsb-tools
  - PACK=lua-5.2
  - PACK=lua
  - PACK=lxmenu-data
  - PACK=lzo
  - PACK=mtdev
  - PACK=net-tools
  - PACK=nettle
  - PACK=npth
  - PACK=nspr
  - PACK=pth
  - PACK=reiserfsprogs
  - PACK=rpcsvc-proto
  - PACK=rpcsvc
  - PACK=sg3_utils
  - PACK=sgml-common
  - PACK=sharutils
  - PACK=sound-theme-freedesktop
  - PACK=soundtouch
  - PACK=tcsh
  - PACK=time
  - PACK=traceroute
  - PACK=tree
  - PACK=unrar
  - PACK=unzip
  - PACK=which
  - PACK=xdg-user-dirs
  - PACK=xfsprogs
  - PACK=zip
install:
- sudo apt update
- sudo apt install schroot debootstrap git fdupes
- wget https://github.com/cli/cli/releases/download/v1.2.0/gh_1.2.0_linux_amd64.deb
- sudo dpkg -i gh_1.2.0_linux_amd64.deb
script:
- wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
- tar -xf chroot.tar.gz
- mv chroot chroot-old
- tar -xf chroot.tar.gz
- ls
- chmod +x -R ./build-scripts/
- cp -r ./build-scripts/ ./chroot
- sudo mount --bind /dev ./chroot/dev/
- travis_wait 150 sudo chroot ./chroot build-scripts/$PACK.sh
- ls
- fdupes --recurse chroot/ chroot-old/ | sed '/^srv/d; /^$/! s/.*/"&"/' | sudo xargs rm
- sudo rm -rf ./chroot/build-scripts
- sudo rm -rf ./chroot/bin/install_deps
- sudo tar -zcf $PACK -C chroot .
- mkdir out
- cp $PACK ./out/
after_script:
- bash upload.sh
- sudo rm -rf ./chroot
