on:
  workflow_dispatch:
name: Build 1st
jobs:
  build:
    environment: manual
    runs-on: ubuntu-18.04
    strategy:
      matrix: 
        pack: [acpid ,apr ,autoconf ,bubblewrap ,cdparanoia ,compface ,dosfstools ,faac ,faad2 ,fdk-aac ,fftw ,gccgo ,gdc ,gfortran, gcc, g++  ,glm ,gnome-backgrounds ,gnome-video-effects ,gobjc++ ,gobjc ,haveged ,hdparm ,hicolor-icon-theme ,iso-codes ,jansson ,jfsutils ,joe ,libaio ,libatasmart ,libatomic_ops ,libburn ,libcddb ,libdvdread ,libgpg-error ,libisofs ,liblinear ,libmad ,libmnl ,libndb ,libnl ,libogg ,libpaper ,librep ,libsigsegv ,libspiro ,libstatgrab ,libuv ,lsb-tools ,lua-5.2 ,lua ,lxmenu-data ,lzo ,mtdev ,net-tools ,nettle ,npth ,nspr ,pth ,reiserfsprogs ,rpcsvc-proto ,rpcsvc ,sg3_utils ,sgml-common ,sharutils ,sound-theme-freedesktop ,soundtouch ,tcsh ,time ,traceroute ,tree ,unrar ,unzip ,which ,xdg-user-dirs ,xfsprogs ,zip]
    steps:
      - name: Clean
        run: unset $GITHUB_TOKEN
      - name: Compile
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
                sudo apt update
                sudo apt install schroot debootstrap git fdupes
                git clone https://github.com/GarnetOS/package-build .
                wget https://github.com/GarnetOS/package-build/releases/download/chroot-1.1/chroot.tar.gz
                tar -xf chroot.tar.gz
                mv chroot chroot-old
                tar -xf chroot.tar.gz
                ls
                chmod +x -R ./build-scripts/
                cp -r ./build-scripts/ ./chroot
                cp -r ./build-scripts/ ./chroot-old
                sudo mount --bind /dev ./chroot/dev/
                sudo chroot ./chroot build-scripts/${{ matrix.pack }}.sh
                sleep 5
                sudo umount -lf ./chroot/dev/
                #./build-scripts/rem.sh
                ./build-scripts/join.sh
                sudo rm -rf ./chroot/build-scripts
                sudo rm -rf ./chroot/bin/install_deps
                sudo tar -zcf ${{ matrix.pack }} -C chroot .
                mkdir out
                cp ${{ matrix.pack }} ./out/
                gh auth login
                gh release upload v1.0 ${{ matrix.pack }} -R GarnetOS/packages
