name: Archs

on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
          arch: [armv6,armv7,aarch64,amd64,ppc64le,i386]
          distro: [bullseye]
          include:
            - arch: riscv64
              distro: unstable
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install needed binaries
        run: |
          sudo apt update
          sudo apt-get install qemu binfmt-support qemu-user-static -y
          #docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm --privileged aptman/qus -s -- -p x86_64 i386 i486 alpha arm armeb sparc32plus ppc ppc64 ppc64le m68k mips mipsel mipsn32 mipsn32el mips64 mips64el sh4 sh4eb s390x aarch64 aarch64_be hppa riscv32 riscv64 xtensa xtensaeb microblaze microblazeel or1k x86_64
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Download and release
        with:
          arch: ${{matrix.arch}}
          distro: ${{matrix.distro}}
          run: |
            uname -m
