name: Actions Runner Controller Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        version: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - run: |
          echo "🎉 This job uses runner scale set runners!"
          uname -a
